[theme]
primaryColor = "#3B82F6"             # Bleu royal vif
backgroundColor = "#FFFFFF"          # Blanc pur pour la clarté
secondaryBackgroundColor = "#EDE9FE" # Violet lavande très doux (le lien avec la musique)
textColor = "#0F172A"                # Bleu nuit presque noir
font = "sans serif"

[client]
showSidebarNavigation = false

[ui]
hideTopBar = true